### ISSUE TITLE
after delete, show text on slice page that slivers deleted

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#101]
After you delete slivers:
In the status table, show you have no resources?

In the messages table, show something

 _Imported from trac ticket [#101](http://trac.gpolab.bbn.com/proto-ch/ticket/101),  created by ahelsing on 06-05-2012 at 14:20, last modified: 06-08-2012 at 13:23_

**Comment by tcmitchell** [comment]
1. There was already a message indicating that slivers were deleted on the delete page.
 2. Added a row to the status table indicating that _No resources were detected_ if no aggregates reported any resources for this slice.
 3. Added a log message on delete slivers with project and slice contexts so that a message displays in the message table.

That's it for this one.

_Trac comment by tmitchel (github user: tcmitchell) on 06-07-2012 at 12:02_

**Comment by tcmitchell** [comment]
Deletes are logged even if no resources were successfully deleted from the slice. Log deletes conditionally if at least one aggregate successfully deletes resources from the slice.

_Trac comment by tmitchel (github user: tcmitchell) on 06-07-2012 at 16:08_

**Comment by tcmitchell** [comment]
Moved log message into the newly created `if ($success)` block so that deletes are only logged when there really are deletes.

Also fixed the `explode()` error in `print_list()`:
```
PHP Warning:  explode() expects parameter 2 to be string, array given
```
`print_list()` was doing an explode and never using the result. No idea why. I deleted the line and all is well. Also restructured the code a bit so it does less work to the same effect.

_Trac comment by tmitchel (github user: tcmitchell) on 06-08-2012 at 13:23_
