### ISSUE TITLE
error email should report in server local timezone

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1080]
The error email we send uses times in UTC, where the logs are in local time. That's confusing.

EG, an email we received at 12:08 EDT says:
```
Date: 2014-07-01T16:06:29+00:00
Error: Invalid result received from Clearinghouse API:
```

 _Imported from trac ticket [#1080](http://trac.gpolab.bbn.com/proto-ch/ticket/1080),  created by ahelsing on 07-01-2014 at 16:10, last modified: 08-08-2014 at 09:34_

**Comment by ahelsing** [comment]
I'd like to use the date() function instead of gmdate().
However, at least on illyrica, the default timezone is set to UTC. So this still gives a time in UTC.
So either we have to fix what PHP thinks the timezone is, or hard-code a different timezone. Or just stick with UTC.

Here is code to get the time in eastern time:
```
$error_date = date_format(date_create(NULL, timezone_open('America/New_York')), 'c');
```

This goes in portal/www/portal/error-text.php around line 75.


_Trac comment by ahelsing on 07-03-2014 at 16:19_

**Comment by ahelsing** [comment]
So far I still can't avoid hard-coding the TZ. I like that less than using UTC I think.
Setting the TZ in the php.ini file didn't seem to do it.


_Trac comment by ahelsing on 07-17-2014 at 12:17_

**Comment by tcmitchell** [comment]
After a little further investigation, it turns out that `date('c')` uses the local time zone on a test page. The real problem is that the DB utils globally set the default time zone to UTC:
```
date_default_timezone_set('UTC');
```
This setting is desirable for writing dates in the database in UTC, but has the side effect of dates formatted as UTC elsewhere as well.

_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 08:36_

**Comment by tcmitchell** [comment]
An alternate approach, which I will not pursue but want to document, is to set a variable (e.g. '$local_tz') to the current time zone prior to globally setting the time zone to UTC as seen above. Then the '$local_tz' can be used on various places where code needs the local time.


_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 09:33_

**Comment by tcmitchell** [comment]
This issue is not worth fixing. The error email is rarely sent and it is straightforward for an operator to convert time from UTC to the time zone displayed in the log file. The cost to fix it outweighs the potential benefit.

_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 09:34_
