### ISSUE TITLE
Add Jacks editor to Manage RSpecs page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1143]
Add the Jacks editor to:
 * the Manage RSpecs page for editing current or new RSpecs, and
 * ~~ the Add Resources page for creating a new RSpec to submit ~~

 _Imported from trac ticket [#1143](http://trac.gpolab.bbn.com/proto-ch/ticket/1143),  created by bujcich on 08-06-2014 at 13:58, last modified: 01-09-2015 at 09:55_

**Comment by ahelsing** [comment]
ticket #1126 added an editor to the Add Resources page (prototype)

_Trac comment by ahelsing on 09-30-2014 at 14:25_

**Comment by MarshallBrinn** [comment]
I want to make sure I understand the intent of this one.

The idea is to add an "Edit" Button in the list of RSpecs and bring up an RSpec editor (there already is a button for a Viewer). 

Do we want to allow that to only the Owner?

- Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-14-2014 at 15:31_

**Comment by ahelsing** [comment]
On a per RSpec basis, only the RSpec owner can edit the RSpec - just as now there is a button for editing the RSpec description.

We could also add a button for creating a new RSpec to be saved to the DB using Jacks.

_Trac comment by ahelsing on 11-14-2014 at 16:19_

**Comment by MarshallBrinn** [comment]
I have this implemented on branch tkt1142_edit_rspec.

A few comments:
 - I changed the previous 'Edit' button to read 'Edit Info'. The new button reads 'Edit RSpec'.
 - The buttons on the editor read 'Save' and 'Cancel'. But the Save is not greyed out when there's no pending change. Jacks provides a topology-change event but not an event for any change. There's no way (that I can tell) when there are pending changes.
 - There's the same problem that's already been reported to Jon. When you save an RSpec and re-read it, the name of the site becomes the Jacks ID rather than the name of the site. As I say, Jon knows about it.

I'll leave this open for Tom and Aaron to look at (after New Years) and we show it to experimenter support at some point.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-11-2014 at 13:44_

**Comment by MarshallBrinn** [comment]
Sorry, that's tkt1143_edit_rspec

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-11-2014 at 13:49_

**Comment by MarshallBrinn** [comment]
Checked this into develop. Note the existing problems listed above which are on Jon's plate.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-09-2015 at 09:55_
