### ISSUE TITLE
Attempt to renew certificate fails with "Multiple rows.." error

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#1153]
As user lnever2, tried to renew my certificate which had expired a few weeks ago but ran into a failure:

 1. selected GENI Certificate Renewal
 2. Clicked on "Generate Combined Certificate and Key File" button

the above resulted in the following failure:

[SERVER] SERVER_ERROR (Multiple rows found for member_id 7d7822f6-0e09-4d7a-88fc-f39299079dd8 in outside certificate table.)

 _Imported from trac ticket [#1153](http://trac.gpolab.bbn.com/proto-ch/ticket/1153),  created by lnevers on 08-20-2014 at 16:26, last modified: 09-03-2014 at 15:52_

**Comment by tcmitchell** [comment]
Three member ids have this issue: 
```
select o1.member_id from ma_outside_cert o1, ma_outside_cert o2 where o1.member_id = o2.member_id and o1.id != o2.id;
              member_id
--------------------------------------
 7d7822f6-0e09-4d7a-88fc-f39299079dd8
 7d7822f6-0e09-4d7a-88fc-f39299079dd8
 b458197e-7161-478f-b169-2a46c03484fd
 b458197e-7161-478f-b169-2a46c03484fd
 cc0e5b11-180d-4b65-aaa6-4d98706c11eb
 cc0e5b11-180d-4b65-aaa6-4d98706c11eb
(6 rows)
```

The expiration dates are interesting because they are either identical or very close together:
```
select id, member_id, expiration from ma_outside_cert where member_id in ('7d7822f6-0e09-4d7a-88fc-f39299079dd8', 'b458197e-7161-478f-b169-2a46c03484fd', 'cc0e5b11-180d-4b65-aaa6-4d98706c11eb') order by member_id;
 id  |              member_id               |     expiration      
-----+--------------------------------------+---------------------
 287 | 7d7822f6-0e09-4d7a-88fc-f39299079dd8 | 2014-08-08 17:16:58
 288 | 7d7822f6-0e09-4d7a-88fc-f39299079dd8 | 2014-08-08 17:16:58
 346 | b458197e-7161-478f-b169-2a46c03484fd | 2014-09-20 19:06:21
 347 | b458197e-7161-478f-b169-2a46c03484fd | 2014-09-20 19:07:56
 704 | cc0e5b11-180d-4b65-aaa6-4d98706c11eb | 2015-03-17 17:50:47
 705 | cc0e5b11-180d-4b65-aaa6-4d98706c11eb | 2015-03-17 17:50:47
(6 rows)
```

I wonder if we have some sort of condition where a page gets refreshed and a new row gets written to the table accidentally.

In the first case ("7d7822f6") the certificates are different. I didn't check the other two cases.

_Trac comment by tmitchel (github user: tcmitchell) on 08-21-2014 at 12:20_

**Comment by tcmitchell** [comment]
It looks like the MA used to allow multiple rows in the outside cert table. That was changed on May 1, 2014 to update the row if it exists, or insert if it does not exist. This would prevent multiple ma_outside_cert rows for a user.

I deleted the the row with the lower id for each of these certificates, effectively keeping the second certificate. That matches the behavior when looking up the certificates, which overwrote the first certificate with the second as it looped through the rows.

No code changes have been made for this ticket, and I don't think any are needed. All three users created these certificates before the fix for renewal went live.

_Trac comment by tmitchel (github user: tcmitchell) on 09-03-2014 at 15:52_
