### ISSUE TITLE
validateRSpec insufficient

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1229]
In tool-rspec-parse, the validateRSpec function fails to detect invalid XML.

The attached RSpec appears to be treated as valid, where it is missing the open less-than tag on the single node.

 _Imported from trac ticket [#1229](http://trac.gpolab.bbn.com/proto-ch/ticket/1229),  created by ahelsing on 11-07-2014 at 10:03, last modified: 04-14-2015 at 11:15_

**Comment by ahelsing** [comment]
_ahelsing attached [vic-bad-rspec.xml](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1229/vic-bad-rspec.xml) on 11-07-2014 at 10:03_

**Comment by MarshallBrinn** [comment]
This appears to be fixed with other more recent changes to XML parsing and error detecting. 

The file as given produces this (correct) error message:

ERROR: This RSpec is invalid: Mismatched tag at line 14, column 10

Adding the missing "<" on line 3 causes the file to load correctly.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-14-2015 at 11:15_
