### ISSUE TITLE
add resources reads rspec only onChange

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1230]
When a user picks an RSpec, if you pick the already selected RSpec, then no event fires.

Specifically, if the user edits the previously selected RSpec file and then re-selects the same file, then the onChange event does not fire, and the new RSpec is not read.

Perhaps the onBlur event can help here?

 _Imported from trac ticket [#1230](http://trac.gpolab.bbn.com/proto-ch/ticket/1230),  created by ahelsing on 11-07-2014 at 10:17, last modified: 12-02-2014 at 10:35_

**Comment by MarshallBrinn** [comment]
Well, I"m not sure there's a real problem here. If you go to 'choose rspec…' and then back to the original rspec, there is an event. I'm not sure what gesture we'd expect to cause this to re-load. Just clicking on the menu and releasing? This is general semantics of HTML pull downs that they don't fire unless a change has been made.

I suggest we don't fix this.

- Marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 12-02-2014 at 10:03_

**Comment by ahelsing** [comment]
Probably right.

_Trac comment by ahelsing on 12-02-2014 at 10:35_
