### ISSUE TITLE
slice jacks ready highlighting broken for ExoSM

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1231]
Niky reports:
```
I made a reservation through ExoSM and then loaded the beta version of Jacks. My resources came from UH
the resources are ready but the boxes are not green. Screenshot here:
http://grab.by/BZmW

I don't know if it has to do with the fact the the AM is ExoSM but the component manager id is UH. 
```

 _Imported from trac ticket [#1231](http://trac.gpolab.bbn.com/proto-ch/ticket/1231),  created by ahelsing on 11-07-2014 at 12:05, last modified: 01-16-2015 at 16:35_

**Comment by MarshallBrinn** [comment]
I think the issue is that Jacks holds onto the comonent_id from the manifest as the 'aggregate_id' in the node in the topology. There is no record of the component_manager_id so we can't match the Jacks nodes (which are in terms of individual EG racks) against the status that is returned (which points to ExoSM).

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-10-2014 at 10:21_

**Comment by MarshallBrinn** [comment]
Jon Duerig put the support in the latest devel push to keep sliver_urns around in the Jacks topology. With that release, I put in new code (in jacks-app.js) to use sliver_id against resourceURN to match status returns. This works on the source=devel branch, but not on the source=stable branch. Once the stable has the new capability it will work for everyone.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-16-2015 at 16:35_
