### ISSUE TITLE
Delete All in Jacks Add Resources does not clear selection dropdown

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1246]
Hitting Delete All in the Jacks instance in Jacks Add Resources clears out your RSpec.

But the selection drop-down for selecting from the portal, or the text area, or the file selected, all do not change. So those UI elements suggest you have a current RSpec selected, while the rest of the page thinks you have none.

This is a follow on from http://trac.gpolab.bbn.com/proto-ch/ticket/1191#comment:3

 _Imported from trac ticket [#1246](http://trac.gpolab.bbn.com/proto-ch/ticket/1246),  created by ahelsing on 12-02-2014 at 15:35, last modified: 12-03-2014 at 14:13_

**Comment by MarshallBrinn** [comment]
Here's the deal. 

When you hit 'delete all' on jacks, you get a change-topology event which shows that your new topology has no nodes (no link, one site) and a corresponding rspec. But you can't tell this from a user who deliberately loaded an empty rspec from the portal, a URL, a paste or a file. So any handling of an empty rspec change-topology event would need to handle these cases in the same way. 

If it is okay to erase the indication of a user action when they load an empty rspec, then I've got that fix ready on a branch. But if we want to distinguish between these cases ("delete all" vs. a user load rspec action) then we'll probably need Jon Duerig to add a flag indicating that the change-topology was due to a delete-all event.

My vote: it is probably okay to erase the indication that the user loaded an empty rspec and treat it as though they hit "delete all". Not worth using one of our few Duerig tokens.

**Comment by MarshallBrinn** [comment]
OK, I'm going to push this a little further. I suggest that any time someone edits the topology on Jacks, we should erase the file/URL/paste/Portal info, since what is in Jacks is no longer consistent with what was originally loaded. That is, every time we get a change-topology, we should clear out those fields. I'm going to experiment with how hard this is.

**Comment by MarshallBrinn** [comment]
OK, all set. I have a fix for this. Whenever any Jacks edit action makes the currently displayed topology contradict the file/RSpec/text/URL widget, the widget is cleared out. Sitting on branch tkt1246_deleteall_clear_jacks pending review.

**Comment by MarshallBrinn** [comment]
Closing #1246. Looks good.
