### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1259]
We _may_ have a memory leak. Or at least a memory inefficient area of our code.

Found this in the logs:
```
[Mon Dec 15 00:02:04 2014] [error] [client 131.123.61.6] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 46 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 663, referer: https://portal.geni.net/secure/listresources.php?slice_id=3bc1b276-030e-4dda-86b4-f38808da2e24&am_id%5B0%5D=17
```

This is calling Omni to get the manifest from an AM. PHP died doing json_decode of the output from Omni.

See http://stackoverflow.com/questions/561066/php-fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter

That says it might be a memory leak. Try Xdebug.
And "Remember that PHP uses reference counting for managing memory. So if you have circular references, or global variables, those objects won't get recycled. That's usually the root of memory leaks in PHP"

If we really need more memory, "in php.ini file. Edit memory_limit to your desire value"

Other tips are here: https://www.airpair.com/php/fatal-error-allowed-memory-size

 _Imported from trac ticket [#1259](http://trac.gpolab.bbn.com/proto-ch/ticket/1259),  created by ahelsing on 12-16-2014 at 11:11, last modified: 04-14-2015 at 11:37_

**Comment by MarshallBrinn** [comment]
I looked through all the existing portal_error logs on nye. Here are all the instances of this problem:

portal_error.log.17:[Mon Dec 15 00:02:04 2014] [error] [client 131.123.61.6] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 46 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 663, referer: https://portal.geni.net/secure/listresources.php?slice_id=3bc1b276-030e-4dda-86b4-f38808da2e24&am_id%5B0%5D=17
portal_error.log.36:[Tue Aug 05 11:37:09 2014] [error] [client 151.204.184.188] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 40 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 569, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=99a3305a-e9b1-4081-8672-ee96f812723e&am_id[]=92&am_id[]=76&am_id[]=44
portal_error.log.36:[Tue Aug 05 11:37:11 2014] [error] [client 151.204.184.188] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 569, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=99a3305a-e9b1-4081-8672-ee96f812723e&am_id[]=92&am_id[]=76&am_id[]=44
portal_error.log.41:[Thu Jul 03 10:10:13 2014] [error] [client 128.112.139.195] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 53 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/slice.php?slice_id=99a3305a-e9b1-4081-8672-ee96f812723e
portal_error.log.45:[Wed Jun 04 20:51:47 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19
portal_error.log.45:[Fri Jun 06 15:35:42 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19&am_id[]=76&am_id[]=44
portal_error.log.45:[Fri Jun 06 15:35:46 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19&am_id[]=76&am_id[]=44
portal_error.log.45:[Fri Jun 06 15:38:03 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19&am_id[]=76&am_id[]=44
portal_error.log.45:[Fri Jun 06 15:39:19 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19&am_id[]=76&am_id[]=44
portal_error.log.45:[Fri Jun 06 15:39:43 2014] [error] [client 24.140.34.191] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20 bytes) in /usr/share/geni-ch/lib/php/am_client.php on line 490, referer: https://portal.geni.net/secure/sliverstatus.php?slice_id=74bc2cbe-4e73-4785-89f2-a9241502b369&am_id[]=19&am_id[]=76&am_id[]=44


So it happened 1 time 6/4/2014, 5 times 6/6/2014, 1 time 7/3/2014, 2 times 8/5/2014 and then 1 time 12/15/2014. 

No obvious pattern on context (client, recent activity). 

But it hasn't happened in four months so I wonder if the underlying problem has been fixed in our recent reworking of omni calls.

Suggest we monitor and close after next GEC if it hasn't recurred. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-14-2015 at 11:37_

**Comment by MarshallBrinn** [comment]
This has not happened since the report above (last one 12/15/2014). Closing the issue.
