### ISSUE TITLE
uncaught type error in jacks-app

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1330]
Had reservation at multiple AMs
On slice-jacks hit Delete
When polling for manifests, got

Uncaught TypeError: undefined is not a function   jacks-app.js:785
JacksApp.onEpManifest jacks-app.js:785
c underscore-min.js:9 
a.Events.trigger underscore-min.js:9 
success_callback portal-jacks-app.js:61 
(anonymous function) portal-jacks-app.js:114

 _Imported from trac ticket [#1330](http://trac.gpolab.bbn.com/proto-ch/ticket/1330),  created by ahelsing on 03-04-2015 at 11:08, last modified: 03-05-2015 at 13:57_

**Comment by ahelsing** [comment]
I have not reproduced the type error, but I have seen multiple empty sites. And I see the cause of the bug.

A key factor in producing the bug is to have multiple AMs.

_Trac comment by ahelsing on 03-04-2015 at 15:54_

**Comment by ahelsing** [comment]
Applied the fix on nye.

_Trac comment by ahelsing on 03-04-2015 at 16:12_

**Comment by ahelsing** [comment]
The error still happens sometimes. Somehow this.sliceAms is changing from an Array to an Object.

_Trac comment by ahelsing on 03-04-2015 at 17:03_

**Comment by ahelsing** [comment]
Is this related to ticket #1326 where Jacks is double polling status/manifest?

_Trac comment by ahelsing on 03-04-2015 at 17:07_

**Comment by tcmitchell** [comment]
This is an issue with PHP `array_unique`. The HTML page is delivered with a javascript variable `jacks_slice_ams` that should be an array of AM ids. Sometimes this turns into a javascript object instead. The reason is that PHP's `array_unique` _preserves keys_ when it removes elements from an array. The result when there are multiple slivers at a single aggregate is that when the array is `json_encode`d, it turns into a JSON dictionary instead of a JSON array.

Good example:
```
var jacks_slice_ams = [207, 199, 54, 80](109,);
```

Bad example:
```
var jacks_slice_ams = {"0":109,"2":207,"4":199,"8":54,"11":80};
```

The solution should be to use PHP's `array_values` to restore the numeric keys of the array of AMs in the PHP code, always producing a JSON array in the web page.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2015 at 11:39_

**Comment by tcmitchell** [comment]
Triggering this bug requires multiple sites, and multiple resources at at least one of those sites. I replicated it using two ExoGENI VMs at each of two ExoGENI aggregates.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2015 at 11:47_

**Comment by tcmitchell** [comment]
this has been fixed and pushed to `master` as a hotfix branch.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2015 at 13:57_
