### ISSUE TITLE
Auto add slice users to existing slivers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1353]
InstaGENI AMs support `geni_update_users` to add new slice members to existing slivers.

Run this POA command automatically when new members are added to a slice.

 _Imported from trac ticket [#1353](http://trac.gpolab.bbn.com/proto-ch/ticket/1353),  created by ahelsing on 03-31-2015 at 09:20, last modified: 04-09-2015 at 15:08_

**Comment by ahelsing** [comment]
Basically you run "`omni --useSliceMembers --ignoreConfigUsers --useSliceAggregates -V3 poa <slice> geni_update_users`"

From the portal, we could use a bunch of `-a` arguments and remove the `--useSliceAggregates` option. And we can build the omni_config as we usually do and remove both `--useSliceMembers` and `--ignoreConfigUsers`.

The strange bit may be that we add members to a slice on the clearinghouse side, and the portal side is where we make the AM calls.

So options
 * the portal action that causes the CH to add slice members then invokes this command
 * put a button up on the slice page giving you the option of doing this yourself (manually)

_Trac comment by ahelsing on 03-31-2015 at 10:05_

**Comment by ahelsing** [comment]
Niky prefers the portal do something automatically. Niky notes that adding an admin to a project should cause this.

_Trac comment by ahelsing on 04-01-2015 at 14:11_

**Comment by MarshallBrinn** [comment]
Done. This only is invoked on IG AM's. It doesn't use the arguments described above since they don't remove keys of recently removed users. Rather, we make a JSON file with the list of all users (including recently deleted ones, with no keys listed) and add that as an '--optionsfile' argument. We aren't running this in the background so it adds some 3-5 seconds to calls, depending on the heath of the aggregates.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-09-2015 at 14:25_
