### ISSUE TITLE
tool-slices undefined index

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1357]
Found 5 examples of this in the logs:
```
[Thu Apr 09 10:48:05 2015] [error] [client 192.1.19.92] PHP Notice:  Undefined index: e04fe44e-915c-400e-9c47-7331f187c3f8 in /usr/share/geni-ch/lib/php/tool-slices.php on line 246, referer: https://portal.geni.net/secure/project.php?project_id=e04fe44e-915c-400e-9c47-7331f187c3f8&slice_id=fbb14c87-c4c6-4b52-bb01-807580d3b0ae&member_id=
|||
```
Note this is the GEC22 project that was just expired but has 5 slices that expire after the project.

The error appears to say there is no entry for this project_id in the `project_objects`, which is the return from `get_project_slice_member_info` apparently when called with `allow_expired=True`.

 _Imported from trac ticket [#1357](http://trac.gpolab.bbn.com/proto-ch/ticket/1357),  created by ahelsing on 04-09-2015 at 11:44, last modified: 04-21-2015 at 13:50_

**Comment by MarshallBrinn** [comment]
Fixed. The issue is that form the home page, we have tool-projects.php AND tool-slices.php and these both set the same global variable (in this case $project_objects). The former sets it to only contain unexpired projects and the latter doesn't override.

What I've done is to make such slices (that are unexpired but whose project is expired) not accessible from the home page (but is accessible from the slice page or from the expired_projects portion of the projects page).



_Trac comment by mbrinn (github user: MarshallBrinn) on 04-14-2015 at 10:35_
