### ISSUE TITLE
Service Registry cache is never refreshed

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#144]
Now that we've fixed session caching to actually work, the service registry cache is never refreshing.

I logged in, then added pgeni3 to the service registry (bin/add_pgeni3_am.sh), but it did not appear on the slice-add-resources page. I finally deleted all portal cookies (including PHPSESSID) to get the SR cache to refresh.

 _Imported from trac ticket [#144](http://trac.gpolab.bbn.com/proto-ch/ticket/144),  created by tmitchel on 06-20-2012 at 11:49, last modified: 06-21-2012 at 16:48_

**Comment by MarshallBrinn** [comment]
Here's the general survey of how we're using session caching in the portal (as of 6/20/2012):

 * user.php maintains a cache of permission manager information that has a timeout (currently = -1)
 * sr_client.php maintains a cache of the contents of the service registry. No timeout: its a one-time deal.
 * starter-status-bar.php maintains the state of the starter tasks so that they don't need to recomputed. No time out.
 * Everything else (tool-showmessage.php and friends) use 'last message' to hold the most recent information about an action. It is erased once it is shown.

The goal is to make some sort of generic caching service here but I'm a little skeptical, given these different use cases, that we can make something generic that covers all use cases. I think the critical distinction here is between things that SHOULD be cached with some timeout (an approximation of a fresh value), and those things that SHOULDN'T be refreshed because they aren't in the database, have no history, are genuinely session-internal state.

 * The permission manager caching is problematic because we need to know fairly immediately about your new permissions wrt. the project or slice you've just created. That's why it is currently disabled.
 * The last message stuff seems to be fine.
 * The starter_status stuff is problematic because it requires that you satisfy all the starter requirements once during the session. That is, if you uploaded SSH keys and then deleted them. At the next session it will tell you that you haven't completed your starter tasks. There is no sense of history: you have EVER completed these tasks. THAT is what we should be caching.
 * The SR registry stuff is the only thing that I think should be cached with a timeout. (Which of course it isn't).

So we need to rethink our general approach to our use of session information, not just the SR registry nor the problem of timeout and refresh.



_Trac comment by mbrinn (github user: MarshallBrinn) on 06-20-2012 at 14:46_

**Comment by MarshallBrinn** [comment]
Checked in partial fix.

1. We have a new function called 'session_cache' which is used for sr_client and thus any client of the SR registry.
2. We added session_id to all the controllers so that they can use a cached value (with timeout) provided by the sr_client.

We still need to fix the starter_status_bar. And we need to change the user permission stuff to use this new session cache.



_Trac comment by mbrinn (github user: MarshallBrinn) on 06-21-2012 at 15:35_

**Comment by MarshallBrinn** [comment]
On second thought I think we should close this one: there is no problem with the service cache any more. And we'll leave the other ticket about the permission cache open to handle the problem of the permission cache.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-21-2012 at 16:48_
