### ISSUE TITLE
Can not "renew slice & resources until" from the Slice page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1590]
On the slice page, if I select the "renew slice & resources until" option to Renew, nothing happens when I click the Renew button.

However, if I only do "renew slice", then when I click Renew it executes the renew and loads a new page.  Also I can renew resources for a week from the Dashboard.

**Comment by tcmitchell** [comment]
This works fine for me. When I click Renew with the "renew slice & resources until" radio button checked I am taken to `do-renew.php` where my slice and my resources are properly renewed.

Can you provide more information about your use case to help debug?

* What browser are you using?
* Are there any messages or errors in the JavaScript console?
* Did you try to clear your cache and reload the slice page from scratch? If not, can you try that?
* What is the nature of your slice? Does it have many resources at many aggregates? One resource at a single aggregate?
* Can you try on a simple slice with one VM at one aggregate to isolate behavior?
* What is the expiration of your slice and its resources prior to attempting the renew?
* Is this broken for one slice or for all of your slices?
* Can you try on a different browser to compare behavior?

**Comment by seledwards** [comment]
Hi Tom,

I missed your reply before and am about to leave, but I thought I could answer at least some of your questions.

It seems to work on Chrome and Safari but not Firefox.  Vic was able to reproduce it not working in Firefox on his system.

I click the "renew" button with the radiobutton "renew slice & resources until" selected and nothing happens and there is no output in the console.  If I select "renew slice until" I get appropriate behavior.

The slice has a single VM at one aggregate.  

The slice is `urn:publicid:IDN+ch.geni.net:GPO-Project+slice+ssh`. You are a member of the [slice](https://portal.geni.net/secure/slice.php?project_id=f8ed8e57-4a50-4e7e-ab46-c8ae22282d90&slice_id=e3d6a7bc-49ee-484b-a63d-f867fb7ee6aa&member_id=#jacks-app) where I see this behavior.  

The slice is currently set to expire long into the future, but I saw this problem before I renewed it with omni.  I see the same behavior with another slice I tried.

Thanks for your help.

**Comment by tcmitchell** [comment]
I am able to reproduce this issue. It seems to occur on Firefox when the "renew slice & resources until" radio button is selected, and the slice has resources. It does not happen on other browsers or when "renew slice until" is selected or when the slice has no resources (because the "renew slice until" radio button is programmatically selected in this case).

To summarize, I think the following three things must be true to reproduce:

1. Firefox
2. Slice has resources
3. Select "renew slice & resources until" radio button

**Comment by tcmitchell** [comment]
This turned out to be an issue with the way hidden input elements are created and appended. For some reason the code was replacing the form element's html with the old html plus the new form element. That's not a good way to do it. That code has been replaced with jQuery generation of an input element (far less room for syntax errors) and appending the new element to the existing element.

For whatever reason, the replacement of HTML caused Firefox to fail the programmatic form submission.
