### ISSUE TITLE
Make self-asserted email address self-service

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1673]
When a school shares ePPN but does not share email address, the email address must be self-asserted. This is currently a manual process using `geni-assert-email`. Make this a self-service process by allowing a user to enter their email address in a web form. Then send them an email with a verification link. Verifying the email address adds an entry to the `km_asserted_attribute` table so that they can access the portal.

Note that the email address does not have to be a school email address as currently required. As long as they can verify an email address, any address will do. They won't be able to access the account in any way other than their school identity provider.

**Comment by ahelsing** [comment]
* The confirmation email should bcc ch-admins
* The confirmation page must be accessible even though they (still) won't have sent an email address
* If they have not confirmed they must get to the usual self asserted email address page with some indication of what address they supplied the first time, and an option to edit the email address or re-send the confirmation request.

**Comment by ahelsing** [comment]
Adding new table `km_confirm_email` to hold the nonce and email for a given eppn.

`kmnoemail.php` will clear entries from that table that are 7 days old. If you shouldn't be here (no eppn, got email, already asserted email) it redirects. It reads any partially asserted email address to pre fill out a form asking for an email address, which goes to....
New page: `kmsendemail.php` redirects if you're in the wrong place, sends you back to kmnoemail on a bad email address. Otherwise it replaces any existing entry in `km_no_email`, and sends the experimenter email to confirm their address (BCCing admins), and telling them to look for this email.
The email points them to new page `kmconfirmemail.php`.
That page redirects if you're in the wrong place, complains if this is a bad link (id/nonce/eppn triple). Otherwise it puts the email/eppn in `km_asserted_attributes` and removes the entry from `km_confirm_email`.

To make this work properly, added a bunch to the KM CSS and a line to kmheader (to properly show/validate the form, and to support tool-showmessage and its clear button).

Note that this change adds a new DB table; run `kmtool/db/postgresql/update-2.sql` to create this table on an existing portal.
