### ISSUE TITLE
Confusing error message when viewing Specs

### ISSUE THREAD

**Issue by vicraj** [GENI-NSF/geni-portal#1696]
Scenario:
   - User logs into Portal and goes to the RSpecs page
   - User is inactive for a while and gets logged out.  The browser still displays the RSpecs page and so there is no indication that user has been logged out.
   - User clicks on "View" for one of the RSpecs.  User gets a pop-up similar to attachment with an error message. 

Desired behavior:
   - Similar to all other pages, take user back to login page
   - In general, for all pages, it'll be nice to take user to a page that says "You have been logged out due to inactivity.  Click <here> to log back into the Portal." when the user session times out.
![tinygrab screen shot 5-9-16 16 18 07](https://cloud.githubusercontent.com/assets/13670873/15161419/c4161be8-16c3-11e6-86d5-c7e8603eead7.png)

**Comment by tcmitchell** [comment]
Since this is an AJAX request we do not get the benefit of automatic redirection to the discovery page. If we really want to make this functionality similar to other pages we would have to take out the AJAX and do a full page load to view the RSpec on a separate HTML page. And if we really want to do that for _all_ pages, we would have to remove all the AJAX queries that bring the portal into the 21st century and send the portal back to the 20th century. Let's not.

Alternatively, we can trap the login page response and let the user know that their session has timed out, offer to refresh the page for them, which in turn will cause a redirection to the discovery page. Note that this can only be done "on demand", when the user initiates the action by clicking on the view button. If we try to set up an "is-my-session-active" demon we'll end up keeping the session alive, which is counter to the idle timeouts built into the underlying authentication system.

Their is no way for a portal page, residing in the user's browser, to detect that a session has timed out. The browser is not involved in any way with that information, which is a joint decision between the portal server and the user's single sign on system. As far as I know there is no way for portal pages to alert the user that they have been logged out due to inactivity other than passive detection on user-initiated actions.

**Comment by vicraj** [comment]
This is such a "corner case" that it isn't worth spending a lot of time 
and resources on it.  Thanks for looking into it.

< Vic
