### ISSUE TITLE
"Expand" button on Add Resources page hangs.

### ISSUE THREAD

**Issue by vicraj** [GENI-NSF/geni-portal#1720]
Not sure if this is a Portal or a Jacks issue:

When I click on the "Expand" button in the Add Resources page, the Jacks editor hangs.  The only way to get the Portal/Jacks unstuck seems to be to use the browser's back button.  However, when I do that, everything that was on the Jacks is lost.

I tried this with Chrome and Safari.

**Comment by tcmitchell** [comment]
I replicated this issue in Chrome. The javascript console says:

```
slice-add-resources-jacks.js:293 Uncaught ReferenceError: jacks_am_status is not defined
```

The stack trace shows this occurs at [slice-add-resources-jacks.js:293](https://github.com/GENI-NSF/geni-portal/blob/v3.15/portal/www/portal/slice-add-resources-jacks.js#L293).

**Comment by tcmitchell** [comment]
This probably broke in v3.5 (October 2015) when status was added to the Jacks aggregate info to be displayed in the aggregate drop down. Since this is the first report, it appears that the expanded view is a seldom used feature.

Adding `jacks_am_status` to `jacks-editor-app-expanded.php` as we do in `slice-add-resources-jacks.php` will likely fix this issue.
