### ISSUE TITLE
Update omni_php to omni2.0

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#217]
omni_php should be updated to omni2.0

We need to get chinterface, which is only in omni2.0

While there, omni_php should log more, to allow tracking what breaks when something goes wrong

 _Imported from trac ticket [#217](http://trac.gpolab.bbn.com/proto-ch/ticket/217),  created by ahelsing on 09-20-2012 at 09:56, last modified: 09-21-2012 at 17:14_

**Comment by tcmitchell** [comment]
The first problem I see is an issue with the version cache. Instead of returning JSON, `omni_php.py` yields a stack trace. The root error is:
```
[Errno 13] Permission denied: '/var/www/.gcf'
```
The PHP executes as user www-data, whose home directory is "/var/www". We can either disable this feature or hand it a version cache directory. I'm inclined towards the former because we specify the AM API version as part of the command line.

_Trac comment by tmitchel (github user: tcmitchell) on 09-20-2012 at 11:09_

**Comment by tcmitchell** [comment]
"--NoGetVersionCache" doesn't disable the version cache, it causes the information to be refreshed. So we can't disable the cache. Instead, point the cache to a temporary file.

_Trac comment by tmitchel (github user: tcmitchell) on 09-20-2012 at 11:16_

**Comment by tcmitchell** [comment]
Using "--GetVersionCacheName" with a temp file (PHP tempnam()) resolves the issue, and now sliver status works. This is probably not backward compatible with gcf 1.6.2 and earlier, so it will force the portal to gcf 2.0 and higher.

_Trac comment by tmitchel (github user: tcmitchell) on 09-20-2012 at 11:21_

**Comment by tcmitchell** [comment]
This change has been pushed and an email went out discussing the required upgrade. The only incompatibility was this version cache issue.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 17:14_
