### ISSUE TITLE
On slice.php Sliver Status for all AMs is slow

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#245]
The slice page is really slow to load when there are multiple aggregates to query.

 _Imported from trac ticket [#245](http://trac.gpolab.bbn.com/proto-ch/ticket/245),  created by ahelsing on 09-27-2012 at 14:02, last modified: 11-28-2012 at 11:21_

**Comment by ahelsing** [comment]
Some thoughts:

 - parallelize SliverStatus calls
 - cache status info
 - let experimenter specify what AMs to query or all
 - maybe pull sliverstatus onto another page?
 - maybe a refresh button if you want more current than cached info


_Trac comment by ahelsing on 09-27-2012 at 14:02_

**Comment by tcmitchell** [comment]
PHP `proc_open` and friends are a possibility for parallelizing the SliverStatus calls if we choose to go that way. http://php.net/manual/en/function.proc-open.php

_Trac comment by tmitchel (github user: tcmitchell) on 09-28-2012 at 07:24_

**Comment by ahelsing** [comment]
For the demo, just be careful which AMs are in the DB


_Trac comment by ahelsing on 10-04-2012 at 16:10_

**Comment by seledwards** [comment]
Have `slice.php` be rendered with a table via AJAX.

Get list of aggregates:
`/secure/aggregates`
This returns JSON with dictionary of tuple of `(id, name)`.  

Then get status for this slice at each AM:
`/secure/sliverstatus?am=X&sid=Y` 
This can return JSON (or actual HTML but we don't want to do this).
This is used to add a row into the HTML table.

If we can do this in a generic way, then we can do this with sliverstatus, slice, resource, manifest, etc (basically all of the pages).

_Trac comment by sedwards (github user: seledwards) on 11-13-2012 at 14:59_

**Comment by seledwards** [comment]
An initial cut at this is merged onto branch `ajax`.  Still needs some small improvements.  Leaving open.

_Trac comment by sedwards (github user: seledwards) on 11-26-2012 at 19:31_

**Comment by seledwards** [comment]
Modified `amstatus.php` to return a dictionary keyed by `am_id`.  For example, like this:
```
{"9":{"url":"https:\/\/localhost:8001\/","geni_status":"ready"},"10":{"url":"https:\/\/www.pgeni3.gpolab.bbn.com:12369\/protogeni\/xmlrpc\/am\/2.0","geni_status":"no resources"}}
```

Will add fields as I need them.

I updated the javascript appropriately to use this.


_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 19:51_

**Comment by seledwards** [comment]
I merged the `ajax` branch back onto `master`.

I think this ticket is done.  Closing.

_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 20:17_

**Comment by tcmitchell** [comment]
Replying to [sedwards](comment:10):

We had talked about making `amstatus.php` return a list, rather than a structure, to make it more amenable to iteration. Can you say more about the choice to use a hash/map for this?

And why are the forward slashes escaped (with backslashes)?

Here's the data structure we had discussed:
```
[
  {"id": "9",
   "url":"https://localhost:8001/",
   "geni_status":"ready"},
  {"id": "10",
   "url":"https://www.pgeni3.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0",
   "geni_status":"no resources"}
]

The inner structs (members of the list) are treated as JavaScript instances automatically, so it can be a nice feature of which the code can take advantage.

We may also want a status token of some sort so that clients can generate their own strings related to that status, or modify behavior based on status. Here, I'm thinking of integer codes (GENI_READY=1, GENI_NO_RESOURCES=2, GENI_BOOTING=3, etc.) That way if the status code is 2, we can drop the row, for instance. Or are we guaranteeing the strings ("no resources") as constants so clients can vary behavior?

This is all fodder for further discussion, rather than bugs in the implementation. It's a rich (and exciting) capability.

> Modified `amstatus.php` to return a dictionary keyed by `am_id`.  For example, like this:
> {{{
> {"9":{"url":"https:\/\/localhost:8001\/","geni_status":"ready"},"10":{"url":"https:\/\/www.pgeni3.gpolab.bbn.com:12369\/protogeni\/xmlrpc\/am\/2.0","geni_status":"no resources"}}
> ```
> 
> Will add fields as I need them.
> 
> I updated the javascript appropriately to use this.

_Trac comment by tmitchel (github user: tcmitchell) on 11-28-2012 at 11:06_

**Comment by seledwards** [comment]
I decided to use a map instead of a list for the following reasons:
 1. You can still loop through the entries using a `for (item in myDict)` construction.
 2. Using a dictionary allows me to easily pull the one element that I need (since the method that is currently using it only really needs one item)

The urls are as they came from the underlying omni call.  I'll adjust them to get rid of the forward slashes.

The status codes is an interesting idea.  It might be especially helpful because I looked at the AMs which didn't always give a response and it's because they are returning "busy".  So the error codes might be a nice way of handling this case as well.

I was also going to add in the error message string when I go to update the Status page.

Thanks for the suggestions.  I'm sure we'll think of lots of other small improvements.

_Trac comment by sedwards (github user: seledwards) on 11-28-2012 at 11:21_
