### ISSUE TITLE
User management scripts

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#249]
Need scripts for managing user data, without killing the database
 - Clear out an account without deleting it
 - Delete one account
 - Delete one slice?
 - Delete one project?

 _Imported from trac ticket [#249](http://trac.gpolab.bbn.com/proto-ch/ticket/249),  created by ahelsing on 10-01-2012 at 14:23, last modified: 10-01-2012 at 17:11_

**Comment by MarshallBrinn** [comment]
I have checked in delete_account.sh into bin which deletes all CS, PA, SA, LOGGING entries associated with a given member_id. If the second (optional) data_only field is set to false (0), then it also deletes all entries from the MA tables.

I will check in a delete slice and delete project shortly.

- Marshall



_Trac comment by mbrinn (github user: MarshallBrinn) on 10-01-2012 at 16:32_

**Comment by MarshallBrinn** [comment]
Added in delete slice and delete project.

One problem is that if you call delete slice and then click on the link to containing project page, you get an error since the project's slices is cached. I don't think this is worth fixing since it isn't fatal and this is a developer/adminstrator tool. But you should go to the home page after calling delete slice or delete project.

_Trac comment by mbrinn (github user: MarshallBrinn) on 10-01-2012 at 17:11_
