### ISSUE TITLE
send portal-dev-admin email when user's IdP doesn't share enough

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#308]
When a user's home institution does not share enough details, the Portal should email portal-help or portal-dev-admin, so we know of a user that may need help.

The user would, as now, be redirected to an Incommon page.

 _Imported from trac ticket [#308](http://trac.gpolab.bbn.com/proto-ch/ticket/308),  created by ahelsing on 10-24-2012 at 15:30, last modified: 11-05-2012 at 17:09_

**Comment by tcmitchell** [comment]
Unfortunately, we won't know anything about the user other than their identity provider, and thus their home institution. Without attributes we won't have name, email address, etc.

Users are currently redirected to an InCommon page that explains the situation to them and encourages them to speak to their home institution about releasing the attributes. This is the path recommended by InCommon, which is why we do it. They set up this capability for exactly this case.

_Trac comment by tmitchel (github user: tcmitchell) on 10-25-2012 at 11:14_

**Comment by tcmitchell** [comment]
Done.

The full HTTP environment gets sent in an email to portal-dev-admin.

_Trac comment by tmitchel (github user: tcmitchell) on 11-05-2012 at 17:09_
