### ISSUE TITLE
Does slice page show expired slices? should it?

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#346]
SA lookup_slice (by ID) does not include the where clause to exclude expired slices. The result is that if you know the ID you can see a slice. Do we like that?

 _Imported from trac ticket [#346](http://trac.gpolab.bbn.com/proto-ch/ticket/346),  created by ahelsing on 11-27-2012 at 16:28, last modified: 02-08-2013 at 19:42_

**Comment by tcmitchell** [comment]
At a minimum, the lookup_slice method should include the "expired" flag, which it does not currently do. Clients of this method should then honor the flag and behave appropriately.

I think it would be erroneous for this method to pretend that a slice with the matching ID does not exist just because it is expired. There may be valid reasons for a client to want information about both active and expired slices.

_Trac comment by tmitchel (github user: tcmitchell) on 11-28-2012 at 10:22_

**Comment by seledwards** [comment]
Assigning this to the 1.3 milestone as I think this is important for the following reason.

I leave my slice page open in my browser overnight (as I am doing regularly for development and I think I would do regularly as an experimenter).  Overnight my slice expires and I come back in the morning and reload my page.  At this point there is no indication that the slice has expired but meanwhile my stuff doesn't work.  This is very confusing.

We should start by noting on the page that the slice expired.   We may also choose to disable the rest of the page or not as appropriate.

_Trac comment by sedwards (github user: seledwards) on 11-30-2012 at 13:11_

**Comment by seledwards** [comment]
This sounds like it has two pieces:
 1. have `lookup_slice` include the "expired" flag
 2. have `slice.php` honor the "expired" flag

Did both of these.  Closing.



_Trac comment by sedwards (github user: seledwards) on 02-08-2013 at 19:42_
