### ISSUE TITLE
Put SR url in settings.php and use it

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#352]
Many places guess the SR url using the /bin/hostname or the current service's hostname or similar. That's wrong.
Instead, put that url in settings.php

This way, the SR can be on a different host than the other services

 _Imported from trac ticket [#352](http://trac.gpolab.bbn.com/proto-ch/ticket/352),  created by ahelsing on 11-29-2012 at 15:50, last modified: 06-26-2013 at 15:59_

**Comment by tcmitchell** [comment]
Consider using an ini file format for the local settings instead of the current php format. That way it is easier for programs written in other languages (sh, python, C) to load and use the configuration settings.

See http://php.net/manual/en/function.parse-ini-file.php

_Trac comment by tmitchel (github user: tcmitchell) on 11-30-2012 at 08:19_

**Comment by ahelsing** [comment]
The SR URL is now in settings.php
Is it used consistently?

_Trac comment by ahelsing on 06-06-2013 at 12:30_

**Comment by tcmitchell** [comment]
This was fixed under issue #354, in milestone:1.5.

_Trac comment by tmitchel (github user: tcmitchell) on 06-26-2013 at 15:59_
