### ISSUE TITLE
Slice status for individual aggregate not updating

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#357]
On the slice status page of the portal (slice.php), the slice status of individual aggregates does not seem to properly update for aggregates on which there are currently allocated resources.  For aggregates that have no resources, the page quickly reports "no resources".  For aggregates with allocated resources it says "...updating..." indefinitely.

As best I can tell, this makes it impossible to release slivers before expiry if you have Flash local storage turned off (as Flack does not work correctly with local storage turned off).

 _Imported from trac ticket [#357](http://trac.gpolab.bbn.com/proto-ch/ticket/357),  created by eblanton on 12-04-2012 at 12:56, last modified: 03-05-2013 at 16:30_
   CCing: elb@...

**Comment by seledwards** [comment]
A quick look at the log indicates that:
```
am_client invoke_omni_function:JSON result is not parseable: "[\n    "Slice
urn:publicid:IDN+panther:XXX+slice+XXX expires within 1 day(s) on 2012-12-05 00:16:55 UTC\\nReturned status of
slivers on 1 of 1 possible aggregates.", \n    {\n        "https://www.uky.emulab.net:12369/protogeni/xmlrpc/am/2.0": {\n     
  "users": [\n                {\n                    "keys": [\n                        {\n                            "type": "ss
<snip>
```
But the JSON ultimately appears to be truncated.

Is this the log file truncating?  Or truncated JSON causing an issue?

_Trac comment by sedwards (github user: seledwards) on 12-04-2012 at 15:56_

**Comment by seledwards** [comment]
Tom and I dug through the code a bit and the "JSON result is not parseable" message appears on line 330 of `lib/php/am_client.php`.

Right above that is a suspicious `while` loop that is reading some content 1024 characters at a time.  

I'll try replacing that `while` loop with something more [appropriate](http://php.net/manual/en/function.fread.php):
```
<?php
$handle = fopen("http://www.example.com/", "rb");
$contents = '';
while (feof($handle)) {
  $contents .= fread($handle, 8192);
}
fclose($handle);
?>
```

Also I dug through the log and the database and found the 6-node-6-link rspec run at PG Kentucky which seems to have pushed us into that error case and was able to reproduce the error message.

_Trac comment by sedwards (github user: seledwards) on 12-05-2012 at 18:15_

**Comment by ahelsing** [comment]
May be related: Resource status for a sliver (created on UKy) shows errors for InstaGENI and ProtoGENI Utah, but nothing at all for ProtoGENI UKy.  However, 'Details' works and displayse the allocated resources.  I can file a separate ticket for this if you prefer, or believe it is not the same problem.

_Trac comment by eblanton on 12-08-2012 at 14:29_

**Comment by seledwards** [comment]
I tried the new loop and it didn't work.  Will revisit what didn't work.

_Trac comment by sedwards (github user: seledwards) on 01-03-2013 at 14:16_

**Comment by ahelsing** [comment]
see ticket #431

_Trac comment by ahelsing on 03-05-2013 at 15:31_

**Comment by tcmitchell** [comment]
Sorry this took so long to fix. It was hard to reproduce. Niky was able to produce a slice that exhibited the same symptoms (#431) and captured a bunch of extra info. We determined that it was a problem with the raw XML-RPC output from the ProtoGENI AM for sliver status.

ProtoGENI confirmed that this was an error in their AM. MAC addresses that contain only numbers, followed by a single letter 'e', followed only by numbers could be interpreted by their XML-RPC encoder as exponential notation. This caused them to be marked as a double instead of a string in the resulting sliver status structure.

They have posted a fix to the Utah AM. Other ProtoGENI based aggregates will get this fix when they update.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2013 at 16:30_
