### ISSUE TITLE
Join requests should probably show up in one page so that you can address all of them at once

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#376]
I haven't tested this, but I believe that if there are multiple join requests then you will have to handle each one separately which in classes might start being annoying if you get 20-30 account requests all together. 

 _Imported from trac ticket [#376](http://trac.gpolab.bbn.com/proto-ch/ticket/376),  created by nriga on 01-16-2013 at 16:23, last modified: 01-10-2014 at 12:11_

**Comment by ahelsing** [comment]
This was a pain at the GEC tutorial.

Add to the table of outstanding requests a form:
Radio button for Admin, Member, Auditor, Decline, No Action (default)


_Trac comment by ahelsing on 03-25-2013 at 10:36_

**Comment by ahelsing** [comment]
I think Mailman does this pretty well, although it could do it even better. (grin) If you'd like to take a look at that interface, and you aren't a Mailman admin yourself, lemme know.

Or I can sum up: Basically the idea is that you get a page with all the pending requests, and you can individually select what you want to do with each of them; and there's also a "Discard everything I haven't otherwise marked" box at the top. I think something like that, but with a more general "Do this to anything marked No Action" button (so you could decline all, or member all, or whatever, them) would be great.

_Trac comment by jbs on 03-25-2013 at 10:42_

**Comment by ahelsing** [comment]
Is this OBE?

_Trac comment by ahelsing on 07-02-2013 at 11:22_

**Comment by ahelsing** [comment]
Niky, is this still a problem, or can we close this ticket?

_Trac comment by ahelsing on 08-01-2013 at 14:53_

**Comment by seledwards** [comment]
While, bulk upload severely mitigates this issue, we think the ticket still should remain open with a low priority.

It would be nice if this were a page like the slice/project membership management pages.  

_Trac comment by sedwards (github user: seledwards) on 08-29-2013 at 12:29_
