### ISSUE TITLE
Handle case where someone invites another person to join a project twice

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#380]
Niky invited me to join a project which she'd already had me join in November but had forgotten about.

When I clicked on the link in the email I got a message "No project specified for project page".

Do two things:
 1) Don't let someone invite a person who is already in the project
 2) Handle the error case when someone clicks on the invite link for a project they've already joined.

 _Imported from trac ticket [#380](http://trac.gpolab.bbn.com/proto-ch/ticket/380),  created by sedwards on 01-16-2013 at 17:22, last modified: 01-03-2014 at 17:43_

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [Screen Shot 2013-01-16 at 5.19.10 PM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/380/Screen Shot 2013-01-16 at 5.19.10 PM.png) on 01-16-2013 at 17:22_

**Comment by ahelsing** [comment]
The code now checks if an invitee is already a project member, and lists that email as "skipped"instead of sending an invitation.  There was already a skipped list for invalid email addresses, now there is a second list for email addresses already in the project.  If there are no addresses left in the invitation list after these checks, just print the warning and send no emails.

The case where someone in a project clicks on an invite link in an email was already handled with the warning: "You are already in this project" 

_Trac comment by phelinek on 01-03-2014 at 17:43_
