### ISSUE TITLE
Disable actions on expired projects

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#422]
On the home page or in tool-projects or on the project page, disable the create slice and invite members if the project is expired.

Do not list expired projects on the join-project page.

In the PA, check for expiration and return an error for invite and join on an expired project. Create slice is already disallowed at the PA on an expired slice.

 _Imported from trac ticket [#422](http://trac.gpolab.bbn.com/proto-ch/ticket/422),  created by ahelsing on 02-26-2013 at 10:30, last modified: 04-03-2013 at 14:09_

**Comment by innnkkki** [comment]
Also the expired projects should probably not show up in the Home page at all, and in the projects tab maybe show up 
as a separate group of projects (expired projects?) along with the dates they were active. 

This would be nice to have soon, so that people after GEC16 that will probably have joined a couple of projects do not
get confused, but I don't think it is required for GEC16. 

_Trac comment by nriga (github user: innnkkki) on 03-04-2013 at 14:17_

**Comment by MarshallBrinn** [comment]
I have done the following:
 * Put logic into the pa_controller to expire/unexpire projects
 * Put logic in home to not display disabled projects
 * Put logic in projects to show the unexpired and expired projects
 * Made it so that the expired projects cannot have create_slice enabled
 * With appropriate privileges, one can renew an expired project and then it becomes one of the 'live' projects again.

Have not yet fixed "Do not list expired projects on the join-project page".

I think this closes out the concerns of this ticket.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-03-2013 at 14:00_

**Comment by MarshallBrinn** [comment]
Fixed join-project.php to only show unexpired projects. Closing ticket.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-03-2013 at 14:09_
