### ISSUE TITLE
Undefined index in print_rspec

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#436]
From `error.log`:

```
PHP Notice:  Undefined index: value in /var/www/secure/print-text-helpers.php on line 296,
 referer: https://panther.gpolab.bbn.com/secure/home.php?project_id=b228286a-8e3e-40e9-b654-433db483fd09&slice_id=&member_id=
```

 _Imported from trac ticket [#436](http://trac.gpolab.bbn.com/proto-ch/ticket/436),  created by tmitchel on 03-06-2013 at 11:48, last modified: 03-07-2013 at 12:24_

**Comment by MarshallBrinn** [comment]
This is fixed - Sarah put the right changes in print-text-helpers.php The issue is that EG doesn't return the error code 12 (no such slice) but error code 2 (bad URN) when you don't have any resources at a resource. EG probably should fix this. Also they seem to return a structure without a 'value' field.

Tested on panther.

_Trac comment by mbrinn (github user: MarshallBrinn) on 03-07-2013 at 12:24_
