### ISSUE TITLE
user eurumbae@iu.edu shows as NONE

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#462]
In the list of members user eurumbae@iu.edu shows up as NONE, I am guessing it is because he does not have his full name registered, either prevent this from happening
or check and if the Name is NONE print the email address

 _Imported from trac ticket [#462](http://trac.gpolab.bbn.com/proto-ch/ticket/462),  created by nriga on 03-22-2013 at 11:14, last modified: 06-07-2013 at 12:58_

**Comment by ahelsing** [comment]
Which list of members was it where this was true?

I think this was fixed with commit [2312dbea82f20f78808fea23248d5fd9ebfaf3cf](https://github.com/GENI-NSF/geni-portal/commit/2312dbea82f20f78808fea23248d5fd9ebfaf3cf)

The only way this could still happen is if the user has no email address.

_Trac comment by ahelsing on 06-07-2013 at 12:58_
