### ISSUE TITLE
Log message display on home screen may be buggy

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#468]
A user reported that a message that had been available in their "GENI Messages" section on the home screen has disappeared. The screenshot is attached. Looking in the database there are many more messages than those presented within the time constraints of the displayed messages. The specific message in question is "requested to be a project lead".

 _Imported from trac ticket [#468](http://trac.gpolab.bbn.com/proto-ch/ticket/468),  created by tmitchel on 03-25-2013 at 17:31, last modified: 04-03-2013 at 07:16_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [GENI_Messages.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/468/GENI_Messages.png) on 03-25-2013 at 17:31_

**Comment by MarshallBrinn** [comment]
Fixed in do-modify.php. Need to add attributes to any call to log_event in order that the logged events are retrieved in the right context. My interpretation is that the user saw the message as it was created in the green screen but didn't see it in the log message window.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-03-2013 at 07:16_
