### ISSUE TITLE
Make order of aggregates consistent

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#478]
The order of the list of aggregates on the slice pages appears arbitrary and keeps changing.  I suspect it's order is influenced by the last aggregate so get updated, but that's not a good ordering mechanism.

Order the list alphabetically so aggregates at the same location ('Utah') will be listed near each other.

 _Imported from trac ticket [#478](http://trac.gpolab.bbn.com/proto-ch/ticket/478),  created by sedwards on 04-02-2013 at 09:17, last modified: 09-06-2013 at 17:00_

**Comment by tcmitchell** [comment]
The slice page (`slice.php`) and its associated JavaScript use a data structure that orders the aggregates by their ID, an arbitrary and always increasing number. So the ordering on this particular page should consistently be based on when the aggregate was added to the database. Modifying that order in the PHP isn't so bad. The JavaScript looks quite a bit more involved because of its reliance on the AM id as its data structure key.

_Trac comment by tmitchel (github user: tcmitchell) on 09-06-2013 at 15:50_

**Comment by tcmitchell** [comment]
A first pass of this effort is complete. The UI elements should show the aggregates in alphabetical order. Asynchronous javascript calls will still be in am_id order. As asynchronous calls, they will always return out of order, so launching in fixed or random order doesn't matter.

_Trac comment by tmitchel (github user: tcmitchell) on 09-06-2013 at 17:00_
