### ISSUE TITLE
DB schema files missing latest update changes

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#534]
The latest DB update files are not reflected in the base schema definitions. As a result, a clean install is missing key database changes.

Changes to roll in to the base schema and data files:
 - `cs/db/postgresql/update-2.sql`
 - `cs/db/postgresql/update-3.sql`
 - `cs/db/postgresql/update-4.sql`
 - `pa/db/postgresql/update-3.sql`

 _Imported from trac ticket [#534](http://trac.gpolab.bbn.com/proto-ch/ticket/534),  created by ahelsing on 05-15-2013 at 10:37, last modified: 05-15-2013 at 13:07_

**Comment by MarshallBrinn** [comment]
There was a typo in cs/db/postgresql  that was fixed. But otherwise, these changes are, in fact, in the schema, just not as these lines. The effect of these changes are evident in the schema and data files (with the exception listed above).

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-15-2013 at 13:07_
