### ISSUE TITLE
emails from services have wrong hostname

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#593]
Email from the CH when you are made a project lead uses the wrong email address
EG:
```
Congratulations, you have been made a 'Project Lead', meaning you can create GENI Projects, as well as create slices in projects and reserve resources.

Please visit https://ch.geni.net/secure/home.php for more information, or to get started.
```

 _Imported from trac ticket [#593](http://trac.gpolab.bbn.com/proto-ch/ticket/593),  created by ahelsing on 06-05-2013 at 16:21, last modified: 06-07-2013 at 12:51_

**Comment by ahelsing** [comment]
I see no setting that gives the URL of the portal. Nothing in settings.ini or settings.php, nothing under the lib, ma or cs directories. 
The portal is not in the service_registry table, and the entry in ma_client does not list the URL or hostname.

Do we need a new setting?

_Trac comment by ahelsing on 06-07-2013 at 10:55_

**Comment by tcmitchell** [comment]
One of the problems here is that a clearinghouse service is directing a new project lead, for instance, to the portal. But the service probably shouldn't be doing that because it makes an assumption about what tool the experimenter wants to or should use. That feels like it may be an unfortunate coupling.

A simple alternative is to remove the second paragraph of the email altogether. They know how to get to their tool of choice because that's probably how they submitted the project lead request.

_Trac comment by tmitchel (github user: tcmitchell) on 06-07-2013 at 11:04_

**Comment by ahelsing** [comment]
We could also direct people here:
http://groups.geni.net/geni/wiki/SignMeUpPortal#a2b.CreateaGENIProject

That has instructions on what to do.

_Trac comment by ahelsing on 06-07-2013 at 11:25_

**Comment by ahelsing** [comment]
That's what I did.

_Trac comment by ahelsing on 06-07-2013 at 12:51_
