### ISSUE TITLE
Fix message on the portal when followin an approval link

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#617]
Rick was confused when he tried to approve Joe Mambretti's request and got the message:

" Member 1571ad67-de17-4e65-ab08-223098b14620 is already a member of project
3236e07c-587d-411d-83e7-3927dfeb1ff6"

We should probably fix the message to use the actual names of the member and project instead of these hash values, also maybe we can modify the message to say :
"<Name of new member> has already been approved/rejected for the role of <role> by <approver> on <date time>"

Or something similar along these lines. 

It would also be nice if the above message showed up immediately after you pressed the link instead of  trying to approve it and then get the error. 

 _Imported from trac ticket [#617](http://trac.gpolab.bbn.com/proto-ch/ticket/617),  created by nriga on 06-13-2013 at 16:54, last modified: 09-16-2013 at 15:45_

**Comment by ahelsing** [comment]
I fixed the message to print the member and project names instead of the id numbers.  

I didn't make the change to print the message immediately instead of after trying to do the approval.  The portal doesn't readily have the information about project membership - that's handled in the sa.  It would be a bigger task for the portal to retrieve this information before handing the request to the sa - if its important we can revisit in the future. 

_Trac comment by phelinek on 09-16-2013 at 15:45_
