### ISSUE TITLE
Fix warnings in gemini.php

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#641]
Fix two warnings in gemini.php. From the portal error log:
```
[Wed Jun 19 12:19:05 2013] [error] [client X.X.X.X] PHP Warning: 
key_exists() expects parameter 2 to be array, null given in
/var/www/secure/gemini.php on line 122, referer:
https://portal.geni.net/secure/home.php

[Wed Jun 19 12:19:05 2013] [error] [client X.X.X.X] PHP Warning: 
key_exists() expects parameter 2 to be array, null given in
/var/www/secure/gemini.php on line 127, referer:
https://portal.geni.net/secure/home.php
```

These both occur if a user has not created a certificate. A warning is pending, so detect the lack of a certificate instead of looking up a key in null.

 _Imported from trac ticket [#641](http://trac.gpolab.bbn.com/proto-ch/ticket/641),  created by tmitchel on 06-20-2013 at 21:41, last modified: 06-21-2013 at 09:26_

**Comment by ahelsing** [comment]
Fixed by adding a requirement that `$result` return something before getting info for GEMINI. 

Also, since this file hadn't been modified in the SA/PA merge from #540, I also changed references of `$pa_url` to `$sa_url`, defined what `$sa_url` is, and added validity checks to make sure that `$sa_url` and `$ma_url` exist (as seems to be the convention in some of the other files).

_Trac comment by bujcich on 06-21-2013 at 09:26_
