### ISSUE TITLE
pgch needs load balancing

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#650]
pgch is a single process. It handles all Omni, GENI Desktop and Flack clients. It is getting over loaded. consider doing some kind of multi-process, load balancing, putting behing Apache, etc.

 _Imported from trac ticket [#650](http://trac.gpolab.bbn.com/proto-ch/ticket/650),  created by ahelsing on 06-24-2013 at 15:24, last modified: 07-02-2013 at 13:39_

**Comment by MarshallBrinn** [comment]
I added multi-threaded into PGCH. This improves performance (shorter wait times, few time outs) significantly. I will keep this ticket open since we should consider moving PGCH behind apache after GEC17. But the fix is tested and should be included in the next GCF release. The 'threaded' mode is a variable in ch.py which can be turned on or off as desired.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-29-2013 at 11:18_

**Comment by seledwards** [comment]
Putting pgch behind apache is now on #672.  

Closing this ticket.

_Trac comment by sedwards (github user: seledwards) on 07-02-2013 at 13:39_
