### ISSUE TITLE
Naming of GENI Desktop button

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#664]
On the Home page the slice specific GENI Desktop button and the generic GENI Desktop button look the same.  

However, the slice specific button takes you to the slice specific GENI Desktop page which causes the slice to be initialized (which may not be what the user wants).

Hussam asked if we can warn the user in some way (perhaps with a pop up asking them to confirm the action) when they click on the slice specific GENI Desktop button on both the Home page and the Slice page.

 _Imported from trac ticket [#664](http://trac.gpolab.bbn.com/proto-ch/ticket/664),  created by sedwards on 06-27-2013 at 08:37, last modified: 08-29-2013 at 12:08_
   CCing: hussam.nasir@..., nriga@...

**Comment by tcmitchell** [comment]
The specific text chosen by GEMINI is "GENI Desktop for <slicename>". That is implemented in branch `tkt664-gemini` on origin. Screen shots were sent to GEMINI for approval, and a couple of alternate approaches were offered:
 * Have GENI Desktop warn users that their slice will be instrumented before doing it
 * Have button label say "Instrument <slicename> with GEMINI" (or "Instrument with GEMINI")


_Trac comment by tmitchel (github user: tcmitchell) on 06-28-2013 at 13:33_

**Comment by tcmitchell** [comment]
Jim Griffoen responded:

 It would seem that whatever you come up with should also be used for flack, since flack is a slice specific tool as well.

 I personally don't see the need to indicate that the button is for a single slice, but I don't have strong feelings one way or the other.

We'll revisit after the GEC.

_Trac comment by tmitchel (github user: tcmitchell) on 06-29-2013 at 09:53_
