### ISSUE TITLE
For ExoSM show the physical location of resources

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#861]
When reserving resources from ExoSM at details and status view we should include
a field about which CM the separate elements came from. 

 _Imported from trac ticket [#861](http://trac.gpolab.bbn.com/proto-ch/ticket/861),  created by nriga on 10-18-2013 at 10:42, last modified: 02-20-2014 at 17:04_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Just wanted to mention that this came up again.

In particular, if you bind nodes to two different racks via the ExoSM, then you can't tell via the portal what happened.

_Trac comment by sedwards (github user: seledwards) on 01-10-2014 at 11:23_

**Comment by ahelsing** [comment]
The logic that listresources uses (print_rspec) should notice that the authority in the sliver URN is different from that for the requested AM. In this case, search through known AMs to find the pretty AM name if possible. Then add that next to the label "Node 1", etc.

_Trac comment by ahelsing on 01-10-2014 at 11:26_

**Comment by MarshallBrinn** [comment]
Here's what I did, which I think is the right solution to this problem:

Instead of returning the component_name (the last element of the URN) I return the sub-authority of the URN if this is an exogeni.net as the authority. 

E.g. 

component_id="urn:publicid:IDN+exogeni.net:bbnvmsite+node+orca-vm-cloud

returns a component_id of 'bbnvmsite" rather than "orca-vm-cloud" (which is constant over all EG or ExoSM aggregates).

Tested on ExoSM, ExoGENI baremetal and VM's.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-20-2014 at 16:51_

**Comment by ahelsing** [comment]
Maybe I don't follow. What does it show for a bare metal machine? Looks like the component ID for a baremetal machine is
urn:publicid:IDN+exogeni.net:bbnvmsite+node+orca-xcat-cloud

So it used to say orca-xcat-cloud.
Does it now say bbnvmsite? Or some combination of bbnvmsite and orca-xcat-cloud?

I ask because I can't tell if anything on the page now indicates that you have a bare metal node?

_Trac comment by ahelsing on 02-20-2014 at 17:04_
