### ISSUE TITLE
aggregate cache doesn't update

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#895]
I added pgeni3 to my aggregates using add_pgeni3_am.sh, and could see pgeni3 in the service registry. However after more than half an hour I still can't see pgeni3 in my aggregate list on either Firefox or Chrome, where I was already logged into my portal.  I brought up safari and logged in, and pgeni3 shows up in the aggregate list there.

 _Imported from trac ticket [#895](http://trac.gpolab.bbn.com/proto-ch/ticket/895),  created by phelinek on 11-20-2013 at 15:23, last modified: 12-05-2013 at 13:12_

**Comment by tcmitchell** [comment]
In chapidev the services cache is never refreshed. Ever.

_Trac comment by tmitchel (github user: tcmitchell) on 11-20-2013 at 16:09_

**Comment by tcmitchell** [comment]
Services change slowly enough that we don't need a 5 minute cache refresh. Instead, implement a cache flush on logout so that we can force a reload of information by logging out and logging back in. This is sufficient to support development testing and tutorial/demo issue resolution.

_Trac comment by tmitchel (github user: tcmitchell) on 11-21-2013 at 12:26_
