### ISSUE TITLE
Add a link to IdP password reset page on the IdP login page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#904]
The time and place where you are most likely to want to reset your GPO IdP password, is on the GPO IdP Login Page (https://shib-idp.geni.net:8444/idp/Authn/UserPassword).  Add a link there to the password reset page.  

 _Imported from trac ticket [#904](http://trac.gpolab.bbn.com/proto-ch/ticket/904),  created by sedwards on 11-27-2013 at 11:23, last modified: 01-08-2014 at 16:31_
   CCing: dabideen@..., gpo-expt-support@...

**Comment by ahelsing** [comment]
Adding text to the login-help page.

I also have draft text for the login page, but that is harder to test. Waiting for the Shib experts to be back in the new year.


_Trac comment by ahelsing on 12-16-2013 at 14:54_

**Comment by tcmitchell** [comment]
The software changes are complete. The update needs to be installed on the identity provider, which is separate from the portal host. I'm calling this complete and closing this ticket because in the context of the portal software, this one's gone as far as it can go.


_Trac comment by tmitchel (github user: tcmitchell) on 01-08-2014 at 16:31_
