### ISSUE TITLE
Error for operators during outage with portal de-authorized

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#944]
Operators during maintenance mode with the portal de-authorized get an error - suggesting that portalIsAuthorized fails or something in user.php fails.

 _Imported from trac ticket [#944](http://trac.gpolab.bbn.com/proto-ch/ticket/944),  created by ahelsing on 12-18-2013 at 10:44, last modified: 05-27-2014 at 10:29_

**Comment by ahelsing** [comment]
Probably the guards at the MA let the operator query for the inside cert and key and return something that is empty where others get an error. So if user.php was more picky about the cert and key being non empty then it would properly redirect.

_Trac comment by ahelsing on 12-19-2013 at 08:48_

**Comment by MarshallBrinn** [comment]
Fixed in user.php and ma-client.php. We need to check whether the INSIDE_KEY/CERT fields are in the response before setting them and then check if the cert is there (and if not go to kmactivate). Fixed and works in all cases (maintenance and non-maintenance, operator and non-operator). 

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-27-2014 at 10:29_
