### ISSUE TITLE
Files are left in /tmp

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#978]
We see a small number of files left in `/tmp` of the following forms:
 * `USERNAME-key-??????`
 * `USERNAME-cred-??????`
 * `USERNAME-cert-??????`

Figure out why and whether they should be there or should be deleted or reaped.

 _Imported from trac ticket [#978](http://trac.gpolab.bbn.com/proto-ch/ticket/978),  created by tmitchel on 02-25-2014 at 15:46, last modified: 05-25-2014 at 17:27_

**Comment by MarshallBrinn** [comment]
I believe this is fixed in the recent CHAPI fixes. I see no files of these names since 4/17 on cascade (nothing on nye). Let's monitor and then close.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-23-2014 at 13:21_

**Comment by MarshallBrinn** [comment]
This was essentially fixed with the proc_open changes in am_client.php. It used to be that invoke_omni_function called write_omni_config which created temp files but which invoke_omni_function didn't delete (actually, couldn't: the names were gone). Now all that is done in invoke_omni_function and there is no code path that returns without these files being deleted. 

That said, this will leave these files if there's an exception that takes place in the processing within invoke_omni_function. So there are some files that have accumulated since this fix went in but I expect this is a function of testing.

The right fix would be to put the unlinking calls in some "finally" block or a destructor or "catch" block. I'll try to do that.


_Trac comment by mbrinn (github user: MarshallBrinn) on 05-24-2014 at 13:22_

**Comment by MarshallBrinn** [comment]
FYI - I added a new feature to lib/file_utils.php: a class called FileManager which allows you to add files and then the destructor deletes all these files (so it happens whenever you exit whether by exception, early return or normal exit. Consider using it in other PHP modules that create temp files. - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-25-2014 at 17:27_
